import { Project, Agent, Report, Analytics } from '@/types';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Q3 Financial Audit & Risk Assessment',
    status: 'Active',
    progress: 68,
    dueDate: 'Oct 15, 2026',
    description: 'Comprehensive financial audit leveraging AI agents to identify anomalies, assess risk exposure, and generate executive-ready reports across all business units.',
    agentsAssigned: ['CFO Agent', 'Data Analyst', 'QA Agent'],
    tasksCompleted: 14,
    tasksTotal: 21,
    lastActivity: '2 minutes ago',
    priority: 'High',
  },
  {
    id: '2',
    name: 'Global Product Launch — Nexus Platform',
    status: 'Active',
    progress: 42,
    dueDate: 'Nov 1, 2026',
    description: 'Multi-region go-to-market strategy coordinated by the CEO Agent, involving product positioning, competitive benchmarking, and localized marketing campaigns.',
    agentsAssigned: ['CEO Agent', 'Marketing Agent', 'Product Agent'],
    tasksCompleted: 9,
    tasksTotal: 22,
    lastActivity: '15 minutes ago',
    priority: 'Critical',
  },
  {
    id: '3',
    name: 'Competitive Intelligence Report',
    status: 'Completed',
    progress: 100,
    dueDate: 'Sep 30, 2026',
    description: 'Deep-dive market analysis covering 12 competitors across pricing, features, and brand sentiment, synthesized into a strategic positioning roadmap.',
    agentsAssigned: ['Research Agent', 'Data Analyst'],
    tasksCompleted: 18,
    tasksTotal: 18,
    lastActivity: '3 days ago',
    priority: 'Medium',
  },
  {
    id: '4',
    name: 'Cloud Infrastructure Migration',
    status: 'At Risk',
    progress: 55,
    dueDate: 'Oct 31, 2026',
    description: 'Zero-downtime migration from legacy on-prem systems to multi-cloud infrastructure. Agents are monitoring compliance requirements and resolving blockers in real-time.',
    agentsAssigned: ['Operations Agent', 'QA Agent'],
    tasksCompleted: 11,
    tasksTotal: 20,
    lastActivity: '1 hour ago',
    priority: 'High',
  },
  {
    id: '5',
    name: 'Customer Experience Transformation',
    status: 'Planning',
    progress: 12,
    dueDate: 'Dec 15, 2026',
    description: 'End-to-end redesign of the customer journey using AI-driven sentiment analysis, NPS modeling, and personalization engine integration.',
    agentsAssigned: ['Product Agent', 'Research Agent'],
    tasksCompleted: 2,
    tasksTotal: 17,
    lastActivity: '1 day ago',
    priority: 'Medium',
  },
  {
    id: '6',
    name: 'Annual ESG Compliance Report',
    status: 'Planning',
    progress: 5,
    dueDate: 'Jan 31, 2027',
    description: 'Automated environmental, social, and governance (ESG) data collection and reporting in compliance with SEC regulations and global sustainability frameworks.',
    agentsAssigned: ['CFO Agent', 'Research Agent'],
    tasksCompleted: 1,
    tasksTotal: 19,
    lastActivity: '2 days ago',
    priority: 'Low',
  },
];

export const mockAgents: Agent[] = [
  {
    id: '1',
    name: 'Aria — CEO Agent',
    role: 'Strategic Orchestrator',
    status: 'Working',
    lastActive: '2m ago',
    description: 'Coordinates all sub-agents, prioritizes tasks, and synthesizes multi-domain intelligence into executive decisions and workflows.',
    tasksCompleted: 234,
    currentTask: 'Reviewing Q3 budget variance analysis',
    model: 'gemini-2.0-flash',
    capabilities: ['Planning', 'Orchestration', 'Synthesis'],
  },
  {
    id: '2',
    name: 'Atlas — Research Agent',
    role: 'Market Intelligence',
    status: 'Working',
    lastActive: '5m ago',
    description: 'Scours the web, academic papers, and industry databases to surface competitive insights, market trends, and primary research findings.',
    tasksCompleted: 189,
    currentTask: 'Analyzing competitor pricing models',
    model: 'gemini-2.0-flash',
    capabilities: ['Web Search', 'Analysis', 'Report Generation'],
  },
  {
    id: '3',
    name: 'Nova — Product Agent',
    role: 'Product Strategist',
    status: 'Idle',
    lastActive: '18m ago',
    description: 'Manages the product backlog, synthesizes user feedback, and creates detailed feature specifications aligned with business objectives.',
    tasksCompleted: 156,
    currentTask: null,
    model: 'gemini-2.0-flash',
    capabilities: ['Roadmapping', 'Spec Writing', 'Prioritization'],
  },
  {
    id: '4',
    name: 'Vega — Finance Agent',
    role: 'Financial Analyst',
    status: 'Working',
    lastActive: '1m ago',
    description: 'Processes financial data streams, builds forecast models, identifies cost optimization opportunities, and prepares board-ready presentations.',
    tasksCompleted: 312,
    currentTask: 'Running Q3 P&L variance model',
    model: 'gemini-2.0-flash',
    capabilities: ['Financial Modeling', 'Risk Assessment', 'Reporting'],
  },
  {
    id: '5',
    name: 'Echo — Marketing Agent',
    role: 'Brand & Growth',
    status: 'Idle',
    lastActive: '42m ago',
    description: 'Drafts multi-channel campaign briefs, analyzes engagement data, and generates A/B test hypotheses to drive measurable growth outcomes.',
    tasksCompleted: 98,
    currentTask: null,
    model: 'gemini-2.0-flash',
    capabilities: ['Copy Generation', 'Campaign Analysis', 'SEO'],
  },
  {
    id: '6',
    name: 'Zenith — Operations Agent',
    role: 'Process Engineer',
    status: 'Working',
    lastActive: '8m ago',
    description: 'Monitors system health, automates repetitive operations workflows, and proactively surfaces bottlenecks before they impact delivery.',
    tasksCompleted: 267,
    currentTask: 'Monitoring cloud migration pipeline',
    model: 'gemini-2.0-flash',
    capabilities: ['Automation', 'Monitoring', 'Optimization'],
  },
  {
    id: '7',
    name: 'Sage — QA Agent',
    role: 'Quality Assurance',
    status: 'Idle',
    lastActive: '2h ago',
    description: 'Validates agent outputs, checks for factual accuracy, identifies logical inconsistencies, and ensures all deliverables meet enterprise quality standards.',
    tasksCompleted: 445,
    currentTask: null,
    model: 'gemini-2.0-flash',
    capabilities: ['Validation', 'Fact Checking', 'Review'],
  },
  {
    id: '8',
    name: 'Luma — Report Agent',
    role: 'Report Synthesizer',
    status: 'Working',
    lastActive: '3m ago',
    description: 'Aggregates multi-agent findings into polished, structured reports with executive summaries, data visualizations, and actionable recommendations.',
    tasksCompleted: 178,
    currentTask: 'Generating competitive intelligence summary',
    model: 'gemini-2.0-flash',
    capabilities: ['Document Generation', 'Summarization', 'Formatting'],
  },
];

export const mockReports: Report[] = [
  {
    id: '1',
    name: 'Q3_Financial_Performance_Summary.pdf',
    type: 'PDF',
    date: 'Oct 4, 2026',
    size: '3.2 MB',
    author: 'Vega (Finance Agent)',
    status: 'Ready',
    description: 'Comprehensive P&L analysis, variance report, and forward-looking cash flow projections for Q3 2026.',
    tags: ['Finance', 'Board-Ready', 'Q3'],
  },
  {
    id: '2',
    name: 'Nexus_Platform_GTM_Strategy.docx',
    type: 'DOCX',
    date: 'Oct 2, 2026',
    size: '1.8 MB',
    author: 'Aria (CEO Agent)',
    status: 'Ready',
    description: 'Complete go-to-market playbook for the Nexus Platform global launch, including pricing, channel strategy, and launch timeline.',
    tags: ['Product', 'Strategy', 'Launch'],
  },
  {
    id: '3',
    name: 'Competitive_Intelligence_Report_v3.pdf',
    type: 'PDF',
    date: 'Sep 30, 2026',
    size: '5.6 MB',
    author: 'Atlas (Research Agent)',
    status: 'Ready',
    description: 'Detailed analysis of 12 direct competitors across product, pricing, brand, and technology dimensions with strategic recommendations.',
    tags: ['Research', 'Competitive', 'Strategy'],
  },
  {
    id: '4',
    name: 'Cloud_Migration_Risk_Matrix.xlsx',
    type: 'XLSX',
    date: 'Oct 3, 2026',
    size: '890 KB',
    author: 'Zenith (Operations Agent)',
    status: 'Ready',
    description: 'Risk register and mitigation playbook for the infrastructure migration, covering security, compliance, and availability risks.',
    tags: ['Operations', 'Risk', 'Cloud'],
  },
  {
    id: '5',
    name: 'Customer_NPS_Sentiment_Analysis.md',
    type: 'MD',
    date: 'Oct 1, 2026',
    size: '256 KB',
    author: 'Nova (Product Agent)',
    status: 'Ready',
    description: 'AI-synthesized customer sentiment analysis from 10,000+ survey responses, identifying key drivers of NPS and churn risk.',
    tags: ['Product', 'Customer', 'Analytics'],
  },
  {
    id: '6',
    name: 'Q4_Marketing_Campaign_Brief.docx',
    type: 'DOCX',
    date: 'Sep 28, 2026',
    size: '1.1 MB',
    author: 'Echo (Marketing Agent)',
    status: 'Ready',
    description: 'Integrated Q4 campaign brief covering paid media, content, influencer, and event marketing with projected ROI models.',
    tags: ['Marketing', 'Campaigns', 'Q4'],
  },
];

export const mockAnalytics: Analytics[] = [
  { name: 'Jan', value: 412, workflows: 38, savings: 8200 },
  { name: 'Feb', value: 380, workflows: 31, savings: 7600 },
  { name: 'Mar', value: 560, workflows: 52, savings: 11200 },
  { name: 'Apr', value: 498, workflows: 45, savings: 9960 },
  { name: 'May', value: 742, workflows: 67, savings: 14840 },
  { name: 'Jun', value: 695, workflows: 61, savings: 13900 },
  { name: 'Jul', value: 834, workflows: 78, savings: 16680 },
  { name: 'Aug', value: 921, workflows: 88, savings: 18420 },
  { name: 'Sep', value: 1024, workflows: 97, savings: 20480 },
  { name: 'Oct', value: 1187, workflows: 112, savings: 23740 },
];

export const mockActivity = [
  { id: '1', agent: 'Vega', action: 'Completed Q3 P&L variance analysis', time: '2m ago', type: 'success' },
  { id: '2', agent: 'Atlas', action: 'Pulled 847 competitor pricing data points', time: '5m ago', type: 'info' },
  { id: '3', agent: 'Aria', action: 'Delegated infrastructure risk review to Zenith', time: '12m ago', type: 'info' },
  { id: '4', agent: 'Zenith', action: 'Flagged latency spike in EU region cluster', time: '15m ago', type: 'warning' },
  { id: '5', agent: 'Luma', action: 'Generated Competitive Intelligence Report v3', time: '32m ago', type: 'success' },
  { id: '6', agent: 'Nova', action: 'Completed NPS sentiment analysis on 10k responses', time: '1h ago', type: 'success' },
  { id: '7', agent: 'Sage', action: 'Validated financial report — 0 errors detected', time: '1.5h ago', type: 'success' },
  { id: '8', agent: 'Echo', action: 'Draft Q4 marketing brief sent for review', time: '2h ago', type: 'info' },
];
