'use client';
import { useState } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { mockReports } from '@/lib/constants/mockData';
import { Button } from '@/components/ui/button';
import { FileText, Download, Tag, Calendar, User, File } from 'lucide-react';

const typeColors: Record<string, string> = {
  PDF: 'bg-red-500/15 text-red-400',
  DOCX: 'bg-blue-500/15 text-blue-400',
  XLSX: 'bg-green-500/15 text-green-400',
  MD: 'bg-purple-500/15 text-purple-400',
  CSV: 'bg-orange-500/15 text-orange-400',
};

export default function ReportsPage() {
  const [downloading, setDownloading] = useState<string | null>(null);

  const downloadFile = (reportId: string, data: string, filename: string, type: string) => {
    setDownloading(reportId);
    const blob = new Blob([data], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    setTimeout(() => setDownloading(null), 800);
  };

  const generateMarkdownContent = (report: typeof mockReports[0]) => {
    return `# ${report.name}

**Author:** ${report.author}
**Date:** ${report.date}
**Type:** ${report.type}

---

## Summary

${report.description}

## Tags

${report.tags?.join(', ')}

---

*Generated by BoardroomAI — Enterprise AI Operating System*
`;
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Reports</h1>
          <p className="text-muted-foreground">AI-generated documents, analyses, and strategic exports.</p>
        </div>
        <div className="flex items-center gap-2 text-sm text-muted-foreground bg-secondary/50 rounded-lg px-3 py-2">
          <File className="w-4 h-4" />
          {mockReports.length} reports available
        </div>
      </div>

      <div className="grid gap-4">
        {mockReports.map((report) => (
          <Card key={report.id} className="glass-card hover:bg-white/5 transition-colors">
            <CardContent className="p-5">
              <div className="flex flex-col sm:flex-row sm:items-start gap-4">
                {/* Icon + Type */}
                <div className="flex gap-3 items-start">
                  <div className="p-3 bg-secondary/50 rounded-lg shrink-0">
                    <FileText className="w-6 h-6 text-primary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h3 className="font-semibold text-sm sm:text-base">{report.name}</h3>
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${typeColors[report.type] ?? 'bg-secondary text-muted-foreground'}`}>
                        {report.type}
                      </span>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">{report.description}</p>

                    {/* Metadata row */}
                    <div className="flex flex-wrap items-center gap-3 mt-2 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <User className="w-3 h-3" /> {report.author}
                      </span>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3 h-3" /> {report.date}
                      </span>
                      <span>{report.size}</span>
                    </div>

                    {/* Tags */}
                    {report.tags && report.tags.length > 0 && (
                      <div className="flex items-center gap-1 mt-2 flex-wrap">
                        <Tag className="w-3 h-3 text-muted-foreground" />
                        {report.tags.map(tag => (
                          <span key={tag} className="text-xs bg-secondary/60 rounded px-2 py-0.5">{tag}</span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>

                {/* Download buttons */}
                <div className="flex gap-2 sm:ml-auto shrink-0">
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={downloading === report.id}
                    onClick={() => downloadFile(report.id, generateMarkdownContent(report), `${report.id}.md`, 'text/markdown')}
                    className="gap-1"
                  >
                    <Download className="w-3 h-3" /> MD
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={downloading === report.id}
                    onClick={() => downloadFile(report.id, JSON.stringify(report, null, 2), `${report.id}.json`, 'application/json')}
                    className="gap-1"
                  >
                    <Download className="w-3 h-3" /> JSON
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
